import fs from 'node:fs';
import assert from 'node:assert/strict';
const index=fs.readFileSync(new URL('../index.html', import.meta.url),'utf8');
const app=fs.readFileSync(new URL('../app.js', import.meta.url),'utf8');
const release=JSON.parse(fs.readFileSync(new URL('../release.json', import.meta.url),'utf8'));
assert.ok(release.id,'release id must be present');
assert.ok(index.includes(`manifest.webmanifest?release=${release.id}`),'index must reference the current release id');
assert.match(index,/id="choicePicker" class="choice-picker"/);
assert.match(index,/\.choice-picker-panel\{position:fixed/);
assert.doesNotMatch(index,/@media\(max-width:680px\).*\.choice-picker-panel\{left:0!important;right:0!important;bottom:0!important/s);
assert.match(index,/@media\(max-width:680px\).*\.choice-picker-backdrop\{background:transparent/s);
assert.match(index,/@media\(max-width:680px\).*\.choice-picker-head\{display:none\}/s);
assert.match(index,/\.choice-picker-option\{[^}]*min-height:44px/);
assert.match(index,/@media\(max-width:680px\).*\.choice-picker-option\{min-height:44px/s);
assert.match(index,/#tbl td:nth-child\(3\)\{grid-column:1\/-1\}/);
assert.match(app,/function enhanceCustomSelects\(root=document\)/);
assert.match(app,/select\.foodedit,select\.speciesedit,select\.subskilledit,select\.manual-editor-input,select\.nickcandidate/);
assert.match(app,/enhanceCustomSelects\(tb\);/);
assert.match(app,/const searchable=choicePickerOptions\.length>=10/);
assert.match(app,/class="nickcandidate"/);
assert.match(app,/function nicknameCandidatePlaceholder\(rows\)/);
assert.match(app,/rows\.length===1\?`候補：\$\{rows\[0\]\.text\}`/);
assert.match(app,/if\(rows\.length>=8\)break/);
assert.doesNotMatch(app,/class="nickalt\$\{/);
assert.match(app,/speciesOpts=allSpeciesNames\(\)/);
assert.doesNotMatch(app,/class="manual-editor-input manual-species-search"/);
assert.match(app,/function reviewEditorActive\(\)\{if\(!\$\('#choicePicker'\)\?\.hidden\)return true/);
console.log('OK: custom choice UI regression checks passed (mobile anchored dropdown mode)');
